/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.controller;

import java.util.List;
 
import org.fre18.qnt.entity.InvoiceLineItems;
import org.fre18.qnt.service.InvoiceLineItemsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@CrossOrigin(origins ="*", maxAge = 3600)	
@RestController
public class InvoiceLineItemsController {
	
	@Autowired
	InvoiceLineItemsService  invoiceLineItemsService;
	
	@RequestMapping(value="/invoiceLineItemsService", method=RequestMethod.GET)
	@ResponseBody
	public InvoiceLineItems getinvoiceLineItemsService() {
		// TODO Auto-generated method stub
		return invoiceLineItemsService.getOne(1);
	}
	
	@RequestMapping(value="/invoiceLineItemsServices", method=RequestMethod.GET)
	@ResponseBody
	public List<InvoiceLineItems> getinvoiceLineItemsServices() {
		// TODO Auto-generated method stub
		List<InvoiceLineItems> invoiceLineItemsServices = invoiceLineItemsService.findAll();
		return invoiceLineItemsServices;
	}
	
	@RequestMapping(value="/invoiceLineItemsService", method=RequestMethod.POST,produces={MediaType.APPLICATION_JSON_VALUE})
	@ResponseBody
	public InvoiceLineItems addinvoiceLineItemsServices(@RequestBody InvoiceLineItems invoiceLineItems) {
		// TODO Auto-generated method stub
		return invoiceLineItemsService.create(invoiceLineItems);
	}
	
	@RequestMapping(value="/invoiceLineItemsService/{id}", method=RequestMethod.PUT,produces={MediaType.APPLICATION_JSON_VALUE})
	@ResponseBody
	public InvoiceLineItems updateinvoiceLineItemsServices(@PathVariable("id") int id, @RequestBody InvoiceLineItems invoiceLineItemsServices) {
		// TODO Auto-generated method stub
		 
		
		InvoiceLineItems cus = invoiceLineItemsService.getOne(id);
		if(cus != null) {
			/*cus.set(invoiceLineItemsServices.getName_st());
			cus.setAge_st(invoiceLineItemsServices.getAge_st());
			cus.setClass_st(invoiceLineItemsServices.getClass_st());
			cus.setAddress_st(invoiceLineItemsServices.getAddress_st());*/
			
			invoiceLineItemsService.update(cus);
		}
		
		return cus;
	}
	
	@RequestMapping(value="/invoiceLineItemsService/{id}", method=RequestMethod.DELETE,produces={MediaType.APPLICATION_JSON_VALUE})
	@ResponseBody
	public InvoiceLineItems deleteinvoiceLineItemsServices(@PathVariable("id") int id){
		System.out.println("Delete" + id);
		/*invoiceLineItemsServicesDaoImpl.deleteinvoiceLineItemsServices(no); */
		InvoiceLineItems cus = invoiceLineItemsService.getOne(id);
		if(cus != null) {
			invoiceLineItemsService.delete(id);
		}
		
		return cus;
	}
}